/**
 * @fileoverview gRPC-Web generated client stub for api.common.proto.customerservice
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.2
// source: api/common/proto/customerservice/customer_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var api_common_proto_header_pb = require('../../../../api/common/proto/header_pb.js')

var api_common_proto_address_pb = require('../../../../api/common/proto/address_pb.js')
const proto = {};
proto.api = {};
proto.api.common = {};
proto.api.common.proto = {};
proto.api.common.proto.customerservice = require('./customer_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.api.common.proto.customerservice.CustomerServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.api.common.proto.customerservice.CustomerServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.api.common.proto.customerservice.GetCustomerRequest,
 *   !proto.api.common.proto.customerservice.GetCustomerResponse>}
 */
const methodDescriptor_CustomerService_GetCustomer = new grpc.web.MethodDescriptor(
  '/api.common.proto.customerservice.CustomerService/GetCustomer',
  grpc.web.MethodType.UNARY,
  proto.api.common.proto.customerservice.GetCustomerRequest,
  proto.api.common.proto.customerservice.GetCustomerResponse,
  /**
   * @param {!proto.api.common.proto.customerservice.GetCustomerRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.api.common.proto.customerservice.GetCustomerResponse.deserializeBinary
);


/**
 * @param {!proto.api.common.proto.customerservice.GetCustomerRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.api.common.proto.customerservice.GetCustomerResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.api.common.proto.customerservice.GetCustomerResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.api.common.proto.customerservice.CustomerServiceClient.prototype.getCustomer =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/api.common.proto.customerservice.CustomerService/GetCustomer',
      request,
      metadata || {},
      methodDescriptor_CustomerService_GetCustomer,
      callback);
};


/**
 * @param {!proto.api.common.proto.customerservice.GetCustomerRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.api.common.proto.customerservice.GetCustomerResponse>}
 *     Promise that resolves to the response
 */
proto.api.common.proto.customerservice.CustomerServicePromiseClient.prototype.getCustomer =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/api.common.proto.customerservice.CustomerService/GetCustomer',
      request,
      metadata || {},
      methodDescriptor_CustomerService_GetCustomer);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.api.common.proto.customerservice.AddCustomerAddressRequest,
 *   !proto.api.common.proto.customerservice.AddCustomerAddressResponse>}
 */
const methodDescriptor_CustomerService_AddCustomerAddress = new grpc.web.MethodDescriptor(
  '/api.common.proto.customerservice.CustomerService/AddCustomerAddress',
  grpc.web.MethodType.UNARY,
  proto.api.common.proto.customerservice.AddCustomerAddressRequest,
  proto.api.common.proto.customerservice.AddCustomerAddressResponse,
  /**
   * @param {!proto.api.common.proto.customerservice.AddCustomerAddressRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.api.common.proto.customerservice.AddCustomerAddressResponse.deserializeBinary
);


/**
 * @param {!proto.api.common.proto.customerservice.AddCustomerAddressRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.api.common.proto.customerservice.AddCustomerAddressResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.api.common.proto.customerservice.AddCustomerAddressResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.api.common.proto.customerservice.CustomerServiceClient.prototype.addCustomerAddress =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/api.common.proto.customerservice.CustomerService/AddCustomerAddress',
      request,
      metadata || {},
      methodDescriptor_CustomerService_AddCustomerAddress,
      callback);
};


/**
 * @param {!proto.api.common.proto.customerservice.AddCustomerAddressRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.api.common.proto.customerservice.AddCustomerAddressResponse>}
 *     Promise that resolves to the response
 */
proto.api.common.proto.customerservice.CustomerServicePromiseClient.prototype.addCustomerAddress =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/api.common.proto.customerservice.CustomerService/AddCustomerAddress',
      request,
      metadata || {},
      methodDescriptor_CustomerService_AddCustomerAddress);
};


module.exports = proto.api.common.proto.customerservice;

