/**
 * @fileoverview gRPC-Web generated client stub for api.common.proto.cartservice
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.2
// source: api/common/proto/cartservice/cart_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var api_common_proto_header_pb = require('../../../../api/common/proto/header_pb.js')
const proto = {};
proto.api = {};
proto.api.common = {};
proto.api.common.proto = {};
proto.api.common.proto.cartservice = require('./cart_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.api.common.proto.cartservice.CartServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.api.common.proto.cartservice.CartServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.api.common.proto.cartservice.GetCartItemsRequest,
 *   !proto.api.common.proto.cartservice.GetCartItemsResponse>}
 */
const methodDescriptor_CartService_GetCartItems = new grpc.web.MethodDescriptor(
  '/api.common.proto.cartservice.CartService/GetCartItems',
  grpc.web.MethodType.UNARY,
  proto.api.common.proto.cartservice.GetCartItemsRequest,
  proto.api.common.proto.cartservice.GetCartItemsResponse,
  /**
   * @param {!proto.api.common.proto.cartservice.GetCartItemsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.api.common.proto.cartservice.GetCartItemsResponse.deserializeBinary
);


/**
 * @param {!proto.api.common.proto.cartservice.GetCartItemsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.api.common.proto.cartservice.GetCartItemsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.api.common.proto.cartservice.GetCartItemsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.api.common.proto.cartservice.CartServiceClient.prototype.getCartItems =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/api.common.proto.cartservice.CartService/GetCartItems',
      request,
      metadata || {},
      methodDescriptor_CartService_GetCartItems,
      callback);
};


/**
 * @param {!proto.api.common.proto.cartservice.GetCartItemsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.api.common.proto.cartservice.GetCartItemsResponse>}
 *     Promise that resolves to the response
 */
proto.api.common.proto.cartservice.CartServicePromiseClient.prototype.getCartItems =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/api.common.proto.cartservice.CartService/GetCartItems',
      request,
      metadata || {},
      methodDescriptor_CartService_GetCartItems);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.api.common.proto.cartservice.MutateCartRequest,
 *   !proto.api.common.proto.cartservice.MutateCartResponse>}
 */
const methodDescriptor_CartService_MutateCart = new grpc.web.MethodDescriptor(
  '/api.common.proto.cartservice.CartService/MutateCart',
  grpc.web.MethodType.UNARY,
  proto.api.common.proto.cartservice.MutateCartRequest,
  proto.api.common.proto.cartservice.MutateCartResponse,
  /**
   * @param {!proto.api.common.proto.cartservice.MutateCartRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.api.common.proto.cartservice.MutateCartResponse.deserializeBinary
);


/**
 * @param {!proto.api.common.proto.cartservice.MutateCartRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.api.common.proto.cartservice.MutateCartResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.api.common.proto.cartservice.MutateCartResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.api.common.proto.cartservice.CartServiceClient.prototype.mutateCart =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/api.common.proto.cartservice.CartService/MutateCart',
      request,
      metadata || {},
      methodDescriptor_CartService_MutateCart,
      callback);
};


/**
 * @param {!proto.api.common.proto.cartservice.MutateCartRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.api.common.proto.cartservice.MutateCartResponse>}
 *     Promise that resolves to the response
 */
proto.api.common.proto.cartservice.CartServicePromiseClient.prototype.mutateCart =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/api.common.proto.cartservice.CartService/MutateCart',
      request,
      metadata || {},
      methodDescriptor_CartService_MutateCart);
};


module.exports = proto.api.common.proto.cartservice;

