/**
 * @fileoverview gRPC-Web generated client stub for api.common.proto.productservice
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.2
// source: api/common/proto/productservice/product_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var api_common_proto_filter_pb = require('../../../../api/common/proto/filter_pb.js')

var api_common_proto_header_pb = require('../../../../api/common/proto/header_pb.js')

var api_common_proto_product_pb = require('../../../../api/common/proto/product_pb.js')

var api_common_proto_category_pb = require('../../../../api/common/proto/category_pb.js')
const proto = {};
proto.api = {};
proto.api.common = {};
proto.api.common.proto = {};
proto.api.common.proto.productservice = require('./product_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.api.common.proto.productservice.ProductServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.api.common.proto.productservice.ProductServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.api.common.proto.productservice.GetProductRequest,
 *   !proto.api.common.proto.productservice.GetProductResponse>}
 */
const methodDescriptor_ProductService_GetProduct = new grpc.web.MethodDescriptor(
  '/api.common.proto.productservice.ProductService/GetProduct',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.api.common.proto.productservice.GetProductRequest,
  proto.api.common.proto.productservice.GetProductResponse,
  /**
   * @param {!proto.api.common.proto.productservice.GetProductRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.api.common.proto.productservice.GetProductResponse.deserializeBinary
);


/**
 * @param {!proto.api.common.proto.productservice.GetProductRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.api.common.proto.productservice.GetProductResponse>}
 *     The XHR Node Readable Stream
 */
proto.api.common.proto.productservice.ProductServiceClient.prototype.getProduct =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/api.common.proto.productservice.ProductService/GetProduct',
      request,
      metadata || {},
      methodDescriptor_ProductService_GetProduct);
};


/**
 * @param {!proto.api.common.proto.productservice.GetProductRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.api.common.proto.productservice.GetProductResponse>}
 *     The XHR Node Readable Stream
 */
proto.api.common.proto.productservice.ProductServicePromiseClient.prototype.getProduct =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/api.common.proto.productservice.ProductService/GetProduct',
      request,
      metadata || {},
      methodDescriptor_ProductService_GetProduct);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.api.common.proto.productservice.GetProductDetailsRequest,
 *   !proto.api.common.proto.productservice.GetProductDetailsResponse>}
 */
const methodDescriptor_ProductService_GetProductDetails = new grpc.web.MethodDescriptor(
  '/api.common.proto.productservice.ProductService/GetProductDetails',
  grpc.web.MethodType.UNARY,
  proto.api.common.proto.productservice.GetProductDetailsRequest,
  proto.api.common.proto.productservice.GetProductDetailsResponse,
  /**
   * @param {!proto.api.common.proto.productservice.GetProductDetailsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.api.common.proto.productservice.GetProductDetailsResponse.deserializeBinary
);


/**
 * @param {!proto.api.common.proto.productservice.GetProductDetailsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.api.common.proto.productservice.GetProductDetailsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.api.common.proto.productservice.GetProductDetailsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.api.common.proto.productservice.ProductServiceClient.prototype.getProductDetails =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/api.common.proto.productservice.ProductService/GetProductDetails',
      request,
      metadata || {},
      methodDescriptor_ProductService_GetProductDetails,
      callback);
};


/**
 * @param {!proto.api.common.proto.productservice.GetProductDetailsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.api.common.proto.productservice.GetProductDetailsResponse>}
 *     Promise that resolves to the response
 */
proto.api.common.proto.productservice.ProductServicePromiseClient.prototype.getProductDetails =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/api.common.proto.productservice.ProductService/GetProductDetails',
      request,
      metadata || {},
      methodDescriptor_ProductService_GetProductDetails);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.api.common.proto.productservice.GetCategorySetRequest,
 *   !proto.api.common.proto.productservice.GetCategorySetResponse>}
 */
const methodDescriptor_ProductService_GetCategorySet = new grpc.web.MethodDescriptor(
  '/api.common.proto.productservice.ProductService/GetCategorySet',
  grpc.web.MethodType.UNARY,
  proto.api.common.proto.productservice.GetCategorySetRequest,
  proto.api.common.proto.productservice.GetCategorySetResponse,
  /**
   * @param {!proto.api.common.proto.productservice.GetCategorySetRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.api.common.proto.productservice.GetCategorySetResponse.deserializeBinary
);


/**
 * @param {!proto.api.common.proto.productservice.GetCategorySetRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.api.common.proto.productservice.GetCategorySetResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.api.common.proto.productservice.GetCategorySetResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.api.common.proto.productservice.ProductServiceClient.prototype.getCategorySet =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/api.common.proto.productservice.ProductService/GetCategorySet',
      request,
      metadata || {},
      methodDescriptor_ProductService_GetCategorySet,
      callback);
};


/**
 * @param {!proto.api.common.proto.productservice.GetCategorySetRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.api.common.proto.productservice.GetCategorySetResponse>}
 *     Promise that resolves to the response
 */
proto.api.common.proto.productservice.ProductServicePromiseClient.prototype.getCategorySet =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/api.common.proto.productservice.ProductService/GetCategorySet',
      request,
      metadata || {},
      methodDescriptor_ProductService_GetCategorySet);
};


module.exports = proto.api.common.proto.productservice;

