/**
 * @fileoverview gRPC-Web generated client stub for api.common.proto.orderservice
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.2
// source: api/common/proto/orderservice/order_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var api_common_proto_header_pb = require('../../../../api/common/proto/header_pb.js')
const proto = {};
proto.api = {};
proto.api.common = {};
proto.api.common.proto = {};
proto.api.common.proto.orderservice = require('./order_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.api.common.proto.orderservice.OrderServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.api.common.proto.orderservice.OrderServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.api.common.proto.orderservice.PlaceOrderRequest,
 *   !proto.api.common.proto.orderservice.PlaceOrderResponse>}
 */
const methodDescriptor_OrderService_PlaceOrder = new grpc.web.MethodDescriptor(
  '/api.common.proto.orderservice.OrderService/PlaceOrder',
  grpc.web.MethodType.UNARY,
  proto.api.common.proto.orderservice.PlaceOrderRequest,
  proto.api.common.proto.orderservice.PlaceOrderResponse,
  /**
   * @param {!proto.api.common.proto.orderservice.PlaceOrderRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.api.common.proto.orderservice.PlaceOrderResponse.deserializeBinary
);


/**
 * @param {!proto.api.common.proto.orderservice.PlaceOrderRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.api.common.proto.orderservice.PlaceOrderResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.api.common.proto.orderservice.PlaceOrderResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.api.common.proto.orderservice.OrderServiceClient.prototype.placeOrder =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/api.common.proto.orderservice.OrderService/PlaceOrder',
      request,
      metadata || {},
      methodDescriptor_OrderService_PlaceOrder,
      callback);
};


/**
 * @param {!proto.api.common.proto.orderservice.PlaceOrderRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.api.common.proto.orderservice.PlaceOrderResponse>}
 *     Promise that resolves to the response
 */
proto.api.common.proto.orderservice.OrderServicePromiseClient.prototype.placeOrder =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/api.common.proto.orderservice.OrderService/PlaceOrder',
      request,
      metadata || {},
      methodDescriptor_OrderService_PlaceOrder);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.api.common.proto.orderservice.ConfirmPaymentRequest,
 *   !proto.api.common.proto.orderservice.ConfirmPaymentResponse>}
 */
const methodDescriptor_OrderService_ConfirmPayment = new grpc.web.MethodDescriptor(
  '/api.common.proto.orderservice.OrderService/ConfirmPayment',
  grpc.web.MethodType.UNARY,
  proto.api.common.proto.orderservice.ConfirmPaymentRequest,
  proto.api.common.proto.orderservice.ConfirmPaymentResponse,
  /**
   * @param {!proto.api.common.proto.orderservice.ConfirmPaymentRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.api.common.proto.orderservice.ConfirmPaymentResponse.deserializeBinary
);


/**
 * @param {!proto.api.common.proto.orderservice.ConfirmPaymentRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.api.common.proto.orderservice.ConfirmPaymentResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.api.common.proto.orderservice.ConfirmPaymentResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.api.common.proto.orderservice.OrderServiceClient.prototype.confirmPayment =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/api.common.proto.orderservice.OrderService/ConfirmPayment',
      request,
      metadata || {},
      methodDescriptor_OrderService_ConfirmPayment,
      callback);
};


/**
 * @param {!proto.api.common.proto.orderservice.ConfirmPaymentRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.api.common.proto.orderservice.ConfirmPaymentResponse>}
 *     Promise that resolves to the response
 */
proto.api.common.proto.orderservice.OrderServicePromiseClient.prototype.confirmPayment =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/api.common.proto.orderservice.OrderService/ConfirmPayment',
      request,
      metadata || {},
      methodDescriptor_OrderService_ConfirmPayment);
};


module.exports = proto.api.common.proto.orderservice;

