/**
 * @fileoverview gRPC-Web generated client stub for api.common.proto.storeservice
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.2
// source: api/common/proto/storeservice/store_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var api_common_proto_filter_pb = require('../../../../api/common/proto/filter_pb.js')

var api_common_proto_header_pb = require('../../../../api/common/proto/header_pb.js')

var api_common_proto_product_pb = require('../../../../api/common/proto/product_pb.js')

var api_common_proto_store_pb = require('../../../../api/common/proto/store_pb.js')
const proto = {};
proto.api = {};
proto.api.common = {};
proto.api.common.proto = {};
proto.api.common.proto.storeservice = require('./store_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.api.common.proto.storeservice.StoreServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.api.common.proto.storeservice.StoreServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.api.common.proto.storeservice.GetStoreRequest,
 *   !proto.api.common.proto.storeservice.GetStoreResponse>}
 */
const methodDescriptor_StoreService_GetStore = new grpc.web.MethodDescriptor(
  '/api.common.proto.storeservice.StoreService/GetStore',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.api.common.proto.storeservice.GetStoreRequest,
  proto.api.common.proto.storeservice.GetStoreResponse,
  /**
   * @param {!proto.api.common.proto.storeservice.GetStoreRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.api.common.proto.storeservice.GetStoreResponse.deserializeBinary
);


/**
 * @param {!proto.api.common.proto.storeservice.GetStoreRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.api.common.proto.storeservice.GetStoreResponse>}
 *     The XHR Node Readable Stream
 */
proto.api.common.proto.storeservice.StoreServiceClient.prototype.getStore =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/api.common.proto.storeservice.StoreService/GetStore',
      request,
      metadata || {},
      methodDescriptor_StoreService_GetStore);
};


/**
 * @param {!proto.api.common.proto.storeservice.GetStoreRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.api.common.proto.storeservice.GetStoreResponse>}
 *     The XHR Node Readable Stream
 */
proto.api.common.proto.storeservice.StoreServicePromiseClient.prototype.getStore =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/api.common.proto.storeservice.StoreService/GetStore',
      request,
      metadata || {},
      methodDescriptor_StoreService_GetStore);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.api.common.proto.storeservice.GetStorePriceForProductRequest,
 *   !proto.api.common.proto.storeservice.GetStorePriceForProductResponse>}
 */
const methodDescriptor_StoreService_GetStorePriceForProduct = new grpc.web.MethodDescriptor(
  '/api.common.proto.storeservice.StoreService/GetStorePriceForProduct',
  grpc.web.MethodType.UNARY,
  proto.api.common.proto.storeservice.GetStorePriceForProductRequest,
  proto.api.common.proto.storeservice.GetStorePriceForProductResponse,
  /**
   * @param {!proto.api.common.proto.storeservice.GetStorePriceForProductRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.api.common.proto.storeservice.GetStorePriceForProductResponse.deserializeBinary
);


/**
 * @param {!proto.api.common.proto.storeservice.GetStorePriceForProductRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.api.common.proto.storeservice.GetStorePriceForProductResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.api.common.proto.storeservice.GetStorePriceForProductResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.api.common.proto.storeservice.StoreServiceClient.prototype.getStorePriceForProduct =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/api.common.proto.storeservice.StoreService/GetStorePriceForProduct',
      request,
      metadata || {},
      methodDescriptor_StoreService_GetStorePriceForProduct,
      callback);
};


/**
 * @param {!proto.api.common.proto.storeservice.GetStorePriceForProductRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.api.common.proto.storeservice.GetStorePriceForProductResponse>}
 *     Promise that resolves to the response
 */
proto.api.common.proto.storeservice.StoreServicePromiseClient.prototype.getStorePriceForProduct =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/api.common.proto.storeservice.StoreService/GetStorePriceForProduct',
      request,
      metadata || {},
      methodDescriptor_StoreService_GetStorePriceForProduct);
};


module.exports = proto.api.common.proto.storeservice;

